env:
    MANIFEST: https://github.com/PixelExperience/manifest.git -b thirteen
    DEVICE: r5x
    OEM: realme
    TARGET: systemimage
    EXTRA_CMD: export SKIP_ABI_CHECKS=true
    LUNCH_COMBO: aosp_$DEVICE-userdebug
    OUTPUT: PixelExperience*.zip

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 240m  
  container:
      image: ubuntu:22.04
      cpu: 8
      memory: 32G



  System-Checker_script:
      - df -h
      - free -h 
      - lscpu
      - nproc

  Setup-Environment_script:
      - mkdir ~/bin
      - PATH=~/bin:$PATH
      - cd ~/bin
      - apt-get -y update
      - apt-get -y install curl
      - curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
      - chmod a+x ~/bin/repo
      - apt install -y git
      - git clone https://github.com/eartinity/scripts.git scripts
      - cd scripts
      - bash setup/android_build_env.sh
  
  Sync_script:
      - mkdir -p ~/work
      - cd ~/work
      - git config --global user.email "pranavjha21@noreply.github.com"
      - git config --global user.name "pranavjha21"
      - repo init --depth=1 -u $MANIFEST
      - repo sync -j4 --force-sync --no-tags --no-clone-bundle
      - git clone https://github.com/eartinity/device_realme_r5x -b pe device/realme/r5x
      - git clone https://github.com/eartinity/vendor_realme_r5x -b thirteen vendor/realme/r5x
      - git clone https://github.com/Amritorock/kernel_realme_r5x.git -b OSS

  Post-Storage-Checker_script:
      - df -h

  Build_script:
      - echo "============================"
      - echo "Starting the Build..."
      - echo "============================"
      - cd ~/work
      - $EXTRA_CMD
      - export CCACHE_DIR=/tmp/ccache
      - export CCACHE_EXEC=$(which ccache)
      - export USE_CCACHE=1
      - ccache -M 15G
      - ccache -o compression=true
      - ccache -z
      - . build/envsetup.sh
      - lunch $LUNCH_COMBO
      - mka $TARGET
     
  Upload_script:
      - echo "============================"
      - echo "Uploading the Build..."
      - echo "============================"
      - cd ~/work
      - cd out/target/product/"$DEVICE"
      - ls -lh
      - pwd
      - chmod 777 *
      - curl --upload-file $(echo $OUTPUT) https://transfer.sh | tee link.txt && echo " "
      - echo " "
      - echo "============================"
      - echo "Build Uploaded!"
      - echo "Please see the link Below-  "
      - echo "----------------------------"
      - cat link.txt && echo " "
      - echo "============================"
    
